version: "3.8"

services:
  mongo:
    image: mongo
    volumes:
      - data:/data/db
  flask:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  react:
    build: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - flask

volumes:
  data: